/**
 * Barrel export snapshot — detects accidental removal or rename of public exports.
 *
 * If this test fails after a code change, it means the public API surface changed.
 * Review the diff: if the removal was intentional (breaking change), update the
 * snapshot. If accidental, fix the export.
 */

import { describe, expect, it } from "vitest";

import * as lib from "@/index";

/**
 * Canonical list of public runtime exports from @middag-io/react.
 * Sorted alphabetically (JS default sort — uppercase before lowercase).
 * Includes the partials surface re-exported via `export * from "@/base/partials"`
 * (DataTable, FormSection, cell renderers, etc.). Type-only exports are erased
 * at runtime and do NOT appear here. The ProductShell + chrome panels
 * (ProductShell, SidebarNav, PageHeader, PageFilterTabs, AppearanceToggle,
 * CommandPalette, HelpPanel, InlineInspector, BoostSearchBar) moved to
 * @middag-io/react-pro and are no longer part of this free surface. The
 * Help/Inspector providers (HelpProvider, useHelp, InspectorProvider) also moved
 * there; the free engine keeps only useInspector + the inspector context.
 * The 17 reui primitives promoted to the barrel root (Badge, Button, Skeleton,
 * Input, Empty, Select, Card, Progress, Alert, AlertDialog, Combobox, Switch,
 * Textarea, Dialog, Collapsible, Spinner, Label — full surface per module) plus
 * `cn` are re-exported via `export * from "@/primitives/reui"` (see
 * src/primitives/reui/index.ts, root barrel only) and appear here.
 * Update this list when intentionally adding/removing exports.
 */
const EXPECTED_EXPORTS = [
  "ActionBar",
  "ActionGridBlock",
  "ActivityTimelineBlock",
  "Alert",
  "AlertAction",
  "AlertDescription",
  "AlertDialog",
  "AlertDialogAction",
  "AlertDialogCancel",
  "AlertDialogContent",
  "AlertDialogDescription",
  "AlertDialogFooter",
  "AlertDialogHeader",
  "AlertDialogMedia",
  "AlertDialogOverlay",
  "AlertDialogPortal",
  "AlertDialogTitle",
  "AlertDialogTrigger",
  "AlertTitle",
  "AnnotatedCell",
  "AuthProvider",
  "AuthShell",
  "Badge",
  "BasicShell",
  "BlockRegion",
  "BooleanCell",
  "Button",
  "Can",
  "Cannot",
  "Card",
  "CardAction",
  "CardContent",
  "CardDescription",
  "CardFooter",
  "CardGridBlock",
  "CardHeader",
  "CardTitle",
  "ChartBlock",
  "Collapsible",
  "CollapsibleContent",
  "CollapsibleTrigger",
  "Combobox",
  "ComboboxChip",
  "ComboboxChips",
  "ComboboxChipsInput",
  "ComboboxCollection",
  "ComboboxContent",
  "ComboboxEmpty",
  "ComboboxGroup",
  "ComboboxInput",
  "ComboboxItem",
  "ComboboxLabel",
  "ComboboxList",
  "ComboboxSeparator",
  "ComboboxTrigger",
  "ComboboxValue",
  "ConfirmationDialog",
  "ContractPage",
  "DashboardLayout",
  "DataTable",
  "DenseTableBlock",
  "DetailPanelBlock",
  "DetailSection",
  "Dialog",
  "DialogClose",
  "DialogContent",
  "DialogDescription",
  "DialogFooter",
  "DialogHeader",
  "DialogOverlay",
  "DialogPortal",
  "DialogTitle",
  "DialogTrigger",
  "DropdownMenu",
  "DropdownMenuCheckboxItem",
  "DropdownMenuContent",
  "DropdownMenuGroup",
  "DropdownMenuItem",
  "DropdownMenuLabel",
  "DropdownMenuPortal",
  "DropdownMenuRadioGroup",
  "DropdownMenuRadioItem",
  "DropdownMenuSeparator",
  "DropdownMenuShortcut",
  "DropdownMenuSub",
  "DropdownMenuSubContent",
  "DropdownMenuSubTrigger",
  "DropdownMenuTrigger",
  "Empty",
  "EmptyContent",
  "EmptyDescription",
  "EmptyHeader",
  "EmptyMedia",
  "EmptyPlaceholder",
  "EmptyStateBlock",
  "EmptyTitle",
  "EntityItem",
  "EntityLink",
  "EntityRoutesProvider",
  "ErrorReporterProvider",
  "FilterBar",
  "FlashProvider",
  "FormField",
  "FormPanelBlock",
  "FormSection",
  "HostSlot",
  "HtmlCell",
  "I18nProvider",
  "ImmersiveShell",
  "InertiaErrorReporter",
  "Input",
  "Label",
  "LazyBlock",
  "LinkCell",
  "LinkGroupCell",
  "LinkListBlock",
  "LogViewer",
  "MIDDAGThemeProvider",
  "MarkdownContent",
  "MarkdownPanelBlock",
  "MenuBar",
  "MetricCardBlock",
  "NavErrorBoundary",
  "Progress",
  "ProgressCell",
  "ProgressProvider",
  "QuickRecordSheet",
  "ResizableSidebar",
  "RichStatusCell",
  "ScopeProvider",
  "Select",
  "SelectContent",
  "SelectGroup",
  "SelectItem",
  "SelectLabel",
  "SelectScrollDownButton",
  "SelectScrollUpButton",
  "SelectSeparator",
  "SelectTrigger",
  "SelectValue",
  "Sidebar",
  "SidebarContent",
  "SidebarFooter",
  "SidebarGroup",
  "SidebarHeader",
  "SidebarInset",
  "SidebarLayout",
  "SidebarMenu",
  "SidebarMenuButton",
  "SidebarMenuItem",
  "SidebarProvider",
  "SidebarRail",
  "SidebarTrigger",
  "Skeleton",
  "Spinner",
  "StackLayout",
  "StatRow",
  "StatusBar",
  "StatusCell",
  "StatusIndicator",
  "StatusStripBlock",
  "StepIndicator",
  "Switch",
  "THEME_CLASSES",
  "THEME_IDS",
  "THEME_SIDEBAR_DIMS",
  "TableOfContents",
  "TabsBlock",
  "Textarea",
  "TimelineList",
  "TimestampCell",
  "Toaster",
  "ToggleGroupControl",
  "Tooltip",
  "TooltipContent",
  "TooltipProvider",
  "TooltipTrigger",
  "TreeView",
  "WizardLayout",
  "applyTheme",
  "badgeVariants",
  "blockRegistry",
  "buttonVariants",
  "cn",
  "cycleAppearance",
  "destroyHostHeaderHeight",
  "getEffectiveTheme",
  "getStoragePrefix",
  "getStoredAppearance",
  "getThemeOverrides",
  "i18n",
  "i18nReady",
  "initDir",
  "initHostHeaderHeight",
  "isLazyBlock",
  "isTranslatableLabel",
  "layoutRegistry",
  "lottie",
  "normalizeLocale",
  "onSystemThemeChange",
  "pageContractSchema",
  "registerBlock",
  "registerCellRenderer",
  "registerDefaultCells",
  "registerDefaultFields",
  "registerDefaultIcons",
  "registerDefaults",
  "registerEntityIcon",
  "registerFieldComponent",
  "registerIcon",
  "registerLayout",
  "registerShell",
  "registerUiStrings",
  "renderLabel",
  "resolveBlock",
  "resolveCellRenderer",
  "resolveEntityIcon",
  "resolveFieldComponent",
  "resolveFieldError",
  "resolveIcon",
  "resolveLayout",
  "resolveShell",
  "setAppearance",
  "setHostHeaderHeight",
  "setHostStringResolver",
  "setStoragePrefix",
  "shellRegistry",
  "storageKey",
  "toggleDir",
  "useAuth",
  "useComboboxAnchor",
  "useEntityRoute",
  "useErrorReporter",
  "useHostString",
  "useInspector",
  "useIsDark",
  "useLazyTabs",
  "useRemember",
  "useScope",
  "useScopeKey",
  "useSidebar",
  "useThemeOverrides",
  "useTranslation",
  "validatePageContract",
];

describe("barrel exports (@middag-io/react)", () => {
  const actualExports = Object.keys(lib).sort();

  it("exports the expected public API surface", () => {
    expect(actualExports).toEqual(EXPECTED_EXPORTS);
  });

  it("has no unexpected exports (detects leaks)", () => {
    const unexpected = actualExports.filter((k) => !EXPECTED_EXPORTS.includes(k));
    expect(unexpected).toEqual([]);
  });

  it("has no missing exports (detects accidental removal)", () => {
    const missing = EXPECTED_EXPORTS.filter((k) => !actualExports.includes(k));
    expect(missing).toEqual([]);
  });
});
